---
name: "Build sensei from AUR"

on: push
#     tags:
#       - "v[0-9]+.[0-9]+.[0-9]+"
#   pull_request:
#     tags:
#       - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create sensei file
        shell: bash
        run: |
          mv assets/aur sensei-bin
          sed -i 's/^pkgname=sensei/pkgname=sensei-bin/' sensei-bin/PKGBUILD
          sed -i 's/^source=("https:\/\/github.com\/edfloreshz\/$pkgname\/releases\/download\/v$pkgver\/$pkgname-amd64.tar.gz")/source=("https:\/\/github.com\/edfloreshz\/${pkgname%-bin}\/releases\/download\/v$pkgver\/${pkgname%-bin}-amd64.tar.gz")/' sensei-bin/PKGBUILD
          sed -i 's/^install -Dm644 release\/LICENSE ${pkgdir}\/usr\/share\/licenses\/${pkgname}\/LICENSE/install -Dm644 release\/LICENSE ${pkgdir}\/usr\/share\/licenses\/${pkgname%-bin}\/LICENSE/' sensei-bin/PKGBUILD
          sed -i 's/^install -Dm644 release\/README.md ${pkgdir}\/usr\/share\/doc\/${pkgname}\/README.md/install -Dm644 release\/README.md ${pkgdir}\/usr\/share\/doc\/${pkgname%-bin}\/README.md/' sensei-bin/PKGBUILD
          sed -i 's/^pkgbase = sensei/pkgbase = sensei-bin/' sensei-bin/.SRCINFO
          sed -i 's/^pkgname = sensei/pkgname = sensei-bin/' sensei-bin/.SRCINFO

      - name: Validate PKGBUILD
        id: validate-pkgbuild
        uses: 2m/arch-pkgbuild-builder@v1.16
        with:
          target: "pkgbuild"
          pkgname: "sensei-bin"

      - name: Validate SRCINFO
        id: validate-srcinfo
        uses: 2m/arch-pkgbuild-builder@v1.16
        with:
          target: "srcinfo"
          pkgname: "sensei-bin"

      - name: Validate binary
        id: validate-binary
        uses: 2m/arch-pkgbuild-builder@v1.16
        with:
          target: "run"
          pkgname: "sensei-bin"
          command: "sns --help"

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v0.0.2
        with:
          file_or_dir: .github/workflows/aur.yml
